use_frameworks!

platform :ios, '10.0'

target 'MVVM_Example' do
  pod 'MVVM', :path => '../'

  target 'MVVM_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
