use_frameworks!

platform :ios, '13.0'

target 'MVVM_Example' do
  pod 'MVVM', :path => '../'

  target 'MVVM_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

post_install do |installer_or_rep|
  installer = installer_or_rep.respond_to?(:installer) ? installer_or_rep.installer : installer_or_rep
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
